micronaut:
    application:
        name: partying
    server:
        port: 8082
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
        enabled: false
    router:
        static-resources:
            swagger:
                paths: "classpath:META-INF/swagger"
            swagger-ui:
                mapping: "/swagger-ui/**"
                paths: "classpath:META-INF/swagger/views/swagger-ui"
                mapping: "/swagger/**"
kafka:
    bootstrap:
        servers: localhost:9091