micronaut:
    application:
        name: auth
    server:
        port: 8081
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
        endpoints:
            login:
                enabled: true
    router:
        static-resources:
            swagger:
                paths: "classpath:META-INF/swagger"
            swagger-ui:
                mapping: "/swagger-ui/**"
                paths: "classpath:META-INF/swagger/views/swagger-ui"
                mapping: "/swagger/**"
jpa:
    default:
        entity-scan:
            packages: github.sagubr
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
                show_sql: true
datasources:
    default:
        url: jdbc:postgresql://localhost:5432/coparty_auth
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres

kafka:
    bootstrap:
        servers: localhost:9091